/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Мост тел одного запроса. Создаётся в Rust, отдаётся в JS как аргумент. */
export declare class BodyIo {
  /**
   * Прочитать следующий чанк тела запроса. `null` = конец.
   * Backpressure JS→Rust: сокет читается только когда JS дёрнул read().
   */
  read(): Promise<Buffer | null>
  /**
   * Записать чанк тела ответа. Резолвится, когда канал принял (backpressure
   * Rust→JS: hyper забирает по мере разгрузки сокета).
   */
  write(chunk: Buffer): Promise<void>
  /** Завершить тело ответа (закрыть канал → hyper видит конец). */
  endWrite(): void
  /** Следующая часть multipart (пропуская хвост недочитанной). `null` = конец формы. */
  nextPart(): Promise<PartMeta | null>
  /** Следующий чанк текущей части. `null` = конец части. */
  readPart(): Promise<Buffer | null>
}

/** Низкоуровневый сервер. Оборачивается JS-классом `Server`. */
export declare class RustServer {
  constructor()
  /**
   * Поднять HTTP/1.1 на `host:port` с таблицей маршрутов.
   *
   * Роутинг/`404`/`405`/авто-`OPTIONS` — в Rust; попадание в лист зовёт
   * `dispatch(req) => Promise<res>`. Неблокирующий (accept-цикл в фоне).
   */
  listen(port: number, host: string, routes: Array<RouteDef>, hasNotFound: boolean, options: ListenOptions, dispatch: (arg: [MatchedRequest, BodyIo]) => Promise<JsResponse>): void
  /**
   * Прогнать запрос через конвейер без сокета (§17, `app.inject`).
   *
   * Выполняется на серверном рантайме (там живут TSFN и состояние), результат
   * приезжает обратно через oneshot. Требует поднятого сервера: маршруты и схемы
   * компилируются в `listen()` — обёртка при необходимости поднимает его на
   * эфемерном порту, но сам запрос через сокет не идёт.
   */
  inject(method: string, path: string, headers: Array<KvPair>, body?: Buffer | undefined | null): Promise<InjectResponse>
  /**
   * Выставить readiness из JS (§11): `app.setReady(false)` снимает под с эндпоинтов,
   * не трогая liveness. Периодический `readinessCheck` пушит сюда же свой результат.
   * До `listen()` — no-op (состояния ещё нет).
   */
  setReady(ready: boolean): void
  /**
   * Graceful shutdown (§10). Резолвится, когда in-flight запросы дожаты
   * (или истёк `shutdownTimeout`). Идемпотентно: повторный вызов — no-op.
   *
   * Порядок: сигнал → accept-цикл закрывает listener (порт свободен сразу) →
   * соединения получают `graceful_shutdown` (h2 — `GOAWAY`) → drain → `done`.
   *
   * Рантайм гасим в отдельном системном потоке через `shutdown_timeout`, а не
   * `shutdown_background`: последний возвращается сразу и **может не уничтожить
   * рантайм вообще** (док tokio). Тогда не дропается `Arc<Shared>`, а вместе с ним
   * живут listener (порт занят) и `ThreadsafeFunction` (держит ref на event loop) —
   * процесс Node не завершается.
   */
  close(): Promise<void>
}

/** Опции CORS с JS-стороны (нормализованы обёрткой). Отсутствие = CORS выключен. */
export interface CorsOptions {
  origins: Array<string>
  methods: Array<string>
  allowedHeaders?: Array<string>
  exposedHeaders?: Array<string>
  credentials: boolean
  maxAge?: number
}

/** Опции HTTP/2 (§6c A1). */
export interface Http2Options {
  maxConcurrentStreams?: number
  initialWindowSize?: number
  maxResetStreamsPerSec?: number
}

/** Ответ `app.inject` (§17): без сокета, но структура та же, что у обычного ответа. */
export interface InjectResponse {
  status: number
  headers: Array<KvPair>
  body: Buffer
}

/**
 * Ответ, который JS-хендлер возвращает (в составе `Promise`).
 *
 * `headers` — упорядоченные пары с допуском повторов (несколько `set-cookie`).
 * `streamed = true` → тело идёт через `BodyIo::write` (канальный `Body`),
 * поле `body` игнорируется. Иначе тело — строка `body`.
 */
export interface JsResponse {
  status?: number
  headers?: Array<KvPair>
  body?: string
  streamed?: boolean
}

/** Пара ключ-значение (для query, где ключи могут повторяться). */
export interface KvPair {
  key: string
  value: string
}

/** Опции сервера, влияющие на вычисление контекста в Rust (§4, §7, §6d). */
export interface ListenOptions {
  customIpHeaders?: Array<string>
  customCountryHeaders?: Array<string>
  requestIdHeader?: string
  /** Жёсткий лимит тела запроса в байтах (авторитетно в Rust). null/отсутствие = без лимита. */
  bodyLimit?: number
  /** Нативный CORS. null/отсутствие = выключен. */
  cors?: CorsOptions
  /** TLS (§12). null/отсутствие = plaintext. */
  tls?: TlsOptions
  /**
   * h2c prior-knowledge на plaintext-порту (§19).
   *
   * `js_name` обязателен: автоконвертация napi даёт `h2C` (буква после цифры
   * поднимается в верхний регистр), обёртка шлёт `h2c` — поле молча терялось.
   */
  h2c?: boolean
  /** Таймаут чтения заголовков в мс (Slowloris, §6c A2). */
  headerReadTimeout?: number
  /** Таймаут ожидания чанка тела запроса в мс (§6c A2) → 408. */
  bodyReadTimeout?: number
  /** Простой соединения без чтения/записи в мс (§6c A2) → закрытие. */
  idleTimeout?: number
  /** Таймаут TLS-хендшейка в мс. */
  handshakeTimeout?: number
  /** Лимит числа заголовков. */
  maxHeaders?: number
  /** Предел размера блока заголовков в байтах (§6c B10) → 431. */
  maxHeaderSize?: number
  /** Дедлайн graceful shutdown в мс (§10). По умолчанию 10с. */
  shutdownTimeout?: number
  /**
   * Пауза между снятием readiness и закрытием listener'а в мс (§10 + §11).
   * Даёт балансировщику убрать под из эндпоинтов до отказа в соединениях.
   */
  preShutdownDelay?: number
  /** Путь Unix-сокета (§6c B9). Задан → слушаем его, `port`/`host` игнорируются. */
  unixPath?: string
  /** Глубина accept-очереди (§6c B9). По умолчанию 1024. */
  backlog?: number
  /** `SO_REUSEPORT` — несколько процессов на одном порту (§6c B9). */
  reusePort?: boolean
  /** `TCP_NODELAY` (§6c B9). По умолчанию включён. */
  noDelay?: boolean
  /** Потолок одновременных соединений (§6c B9). */
  maxConnections?: number
  /** Ждать PROXY protocol v1/v2 на каждом соединении (§6c A4). */
  proxyProtocol?: boolean
  /** Число tokio-воркеров; `0`/отсутствие = авто по cgroup-квоте (§6c A3). */
  workerThreads?: number
  /** Путь liveness-пробы (§11). Пустая строка = выключить. */
  healthPath?: string
  /** Путь readiness-пробы (§11). Пустая строка = выключить. */
  readyPath?: string
  /** Путь метрик Prometheus (§11). Пустая строка = выключить. */
  metricsPath?: string
  /** Отдельный порт для проб/метрик (§11); задан → на основном порту их нет. */
  adminPort?: number
  /** JSON access-log в stdout (§11). */
  accessLog?: boolean
  /** Потолок одновременно обрабатываемых запросов (§6c C5). Сверх — 503. */
  maxConcurrentRequests?: number
  /** Сколько запросов ждут слот сверх лимита (§6c C5). 0 = очереди нет. */
  maxQueue?: number
  /** Сколько ждать в очереди, мс (§6c C5). По умолчанию 1с. */
  queueTimeout?: number
  /** Значение заголовка `Retry-After` в секундах при 503 (§6c C5). */
  retryAfter?: number
  /**
   * Длительность непрерывной перегрузки, после которой снимается readiness, мс
   * (§6c C5). Отсутствие/0 = readiness не трогать.
   */
  overloadShedAfter?: number
  http2?: Http2Options
}

/**
 * Сматченный запрос, передаваемый в JS-диспетчер (один переход границы/запрос).
 *
 * `leaf_id` — индекс листа маршрута в JS-реестре хендлеров; `-1` = notFound.
 * `path` — полный путь (с baseUrl); обёртка снимает префикс для `c.req.path`.
 * `ip`/`ips`/`country`/`id` вычислены в Rust (§7, §6d B2).
 */
export interface MatchedRequest {
  leafId: number
  method: string
  path: string
  queryString?: string
  params: Record<string, string>
  query: Array<KvPair>
  headers: Array<KvPair>
  ip: string
  ips: Array<string>
  country?: string
  id: string
  /**
   * Провалидированные/коэрцированные значения (JSON-строки) — если у листа схема.
   * `c.req.valid('body'|'query'|'params')` в JS доигрывает valibot transform.
   */
  validBody?: string
  validQuery?: string
  validParams?: string
}

/** Per-route опции multipart (нормализованы обёрткой; лимиты в байтах/штуках). */
export interface MultipartOptions {
  maxFileSize?: number
  maxFieldSize?: number
  maxFiles?: number
  maxFields?: number
  allowedMimeTypes?: Array<string>
  allowedExtensions?: Array<string>
}

/** Метаданные части multipart для JS. */
export interface PartMeta {
  name?: string
  filename?: string
  contentType?: string
}

/**
 * Определение маршрута из JS-обёртки (path уже склеен с baseUrl/групповым префиксом).
 * Схемы — JSON Schema как строки (обёртка конвертирует valibot заранее).
 */
export interface RouteDef {
  method: string
  path: string
  leafId: number
  bodySchema?: string
  querySchema?: string
  paramsSchema?: string
  multipart?: MultipartOptions
}

/** TLS-сертификаты (PEM-строки; путь/Buffer резолвит обёртка). */
export interface TlsOptions {
  cert: string
  key: string
}
